require:
  - rubocop-rails
  - rubocop-rspec

inherit_gem:
  rubocop-fjord:
    - config/rubocop.yml
    - config/rails.yml

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/ClassLength:
  Exclude:
    - spec/**/*

Style/NumericLiterals:
  Exclude:
    - spec/**/*

RSpec/MultipleExpectations:
  Exclude:
    - spec/**/*

RSpec/ContextWording:
  Exclude:
    - spec/**/*

RSpec/DescribedClass:
  Exclude:
    - spec/**/*

RSpec/ExampleLength:
  Exclude:
    - spec/**/*

RSpec/NestedGroups:
  Exclude:
    - spec/**/*

RSpec/MultipleMemoizedHelpers:
  Exclude:
    - spec/**/*

RSpec/LetSetup:
  Exclude:
    - spec/models/team_spec.rb

AllCops:
  Exclude:
    - "**/templates/**/*"
    - "**/vendor/**/*"
    - app/views/**/*
    - config/**/*
    - config.ru
    - node_modules/**/*
    - db/migrate/*
    - db/schema.rb
    - storage/**/*
    - tmp/**/*
    - bin/**/*
    - app/controllers/overrides/**/* # devise token authの上書きなので対象外にする
