require:
  - rubocop-rails
  - rubocop-rspec

inherit_gem:
  rubocop-fjord:
    - config/rubocop.yml
    - config/rails.yml

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/ClassLength:
  Exclude:
    - spec/**/*

Style/NumericLiterals:
  Exclude:
    - spec/**/*

RSpec/MultipleExpectations:
  Exclude:
    - spec/**/*

RSpec/ContextWording:
  Exclude:
    - spec/**/*

RSpec/DescribedClass:
  Exclude:
    - spec/**/*

RSpec/ExampleLength:
  Exclude:
    - spec/**/*

AllCops:
  Exclude:
    - "**/templates/**/*"
    - "**/vendor/**/*"
    - app/views/**/*
    - config/**/*
    - config.ru
    - node_modules/**/*
    - db/migrate/*
    - db/schema.rb
    - storage/**/*
    - tmp/**/*
    - bin/**/*
    - app/controllers/api/auth/registrations_controller.rb # devise token authの上書きなので対象外にする
